apiVersion: v1
kind: Service 
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9094
      name: http
      targetPort: 9094
  selector: 
    app.kubernetes.io/name: {{ .Values.name }}
